version: '3'
services:
  gps_service:
    image: gps_service:2022.09
    container_name: gps_service
    environment:
      - GPSUSBPort=/dev/ttyUSB0
      - RedisIP=192.168.0.1
      - RedisPort=16379
      - RedisPassword=zaq1xsw2cde3
    volumes:
      - $PWD/save:/app/save
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command:
      - docker-entrypoint.sh

